package modular

import (
	"github.com/charmbracelet/bubbles/list"
	tea "github.com/charmbracelet/bubbletea"
	huh "github.com/charmbracelet/huh"
	"github.com/charmbracelet/lipgloss"
)

type FeatureListItem struct {
	feature *Feature
}

func (i FeatureListItem) Title() string       { return i.feature.Heading }
func (i FeatureListItem) Description() string { return i.feature.Summary }
func (i FeatureListItem) FilterValue() string { return i.feature.Heading }

func CreateFeatureListModelFromMainModel(m *MainModel, block BlockInterface, features []Feature) *FeatureListModel {
	items := make([]list.Item, len(features))
	for i := range features {
		items[i] = FeatureListItem{feature: &features[i]}
	}

	l := list.New(items, list.NewDefaultDelegate(), 20, 14)
	l.Title = "Features"
	l.SetShowStatusBar(true)
	l.SetFilteringEnabled(true)
	l.SetShowHelp(true)
	l.SetSize(m.Width(), m.Height()-3)

	return &FeatureListModel{
		Block:         block,
		List:          l,
		NavigationCtx: m.NavigationCtx(),
		Parent:        m,
		Features:      &features,
	}
}

type FeatureListModel struct {
	List          list.Model
	NavigationCtx *NavigationContext
	Parent        *MainModel
	Block         BlockInterface
	Features      *[]Feature
}

func (m *FeatureListModel) Init() tea.Cmd {
	return nil
}

func (m *FeatureListModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		if m.List.FilterState() == list.Filtering {
			break
		}
		if msg.String() == "esc" {
			m.NavigationCtx.Pop()
			m.Parent.ModelStack.Pop()
			return m.Parent.ModelStack.Current(), nil
		}
		if msg.String() == "e" {
			if i, ok := m.List.SelectedItem().(FeatureListItem); ok {
				m.List.ResetFilter()
				m.NavigationCtx.Push("Edit Feature")
				form := huh.NewForm(
					huh.NewGroup(
						huh.NewInput().
							Key("heading").
							Title("Heading").
							Value(&i.feature.Heading),
						huh.NewText().
							Key("summary").
							Title("Summary").
							Value(&i.feature.Summary),
						huh.NewSelect[string]().
							Key("icon").
							Title("Icon").
							Options(
								huh.NewOption("Outline Add Column After", "outline-add-column-after"),
								huh.NewOption("Outline Add Column Before", "outline-add-column-before"),
								huh.NewOption("Outline Address Book", "outline-address-book"),
								huh.NewOption("Outline Adjustments Horizontal", "outline-adjustments-horizontal"),
								huh.NewOption("Outline Adjustments Vertical", "outline-adjustments-vertical"),
								huh.NewOption("Outline Align Center", "outline-align-center"),
								huh.NewOption("Outline Align Justify", "outline-align-justify"),
								huh.NewOption("Outline Align Left", "outline-align-left"),
								huh.NewOption("Outline Align Right", "outline-align-right"),
								huh.NewOption("Outline Angle Down", "outline-angle-down"),
								huh.NewOption("Outline Angle Left", "outline-angle-left"),
								huh.NewOption("Outline Angle Right", "outline-angle-right"),
								huh.NewOption("Outline Angle Up", "outline-angle-up"),
								huh.NewOption("Outline Annotation", "outline-annotation"),
								huh.NewOption("Outline API Key", "outline-api-key"),
								huh.NewOption("Outline Archive Arrow Down", "outline-archive-arrow-down"),
								huh.NewOption("Outline Archive", "outline-archive"),
								huh.NewOption("Outline Arrow Down To Bracket", "outline-arrow-down-to-bracket"),
								huh.NewOption("Outline Arrow Down", "outline-arrow-down"),
								huh.NewOption("Outline Arrow Left To Bracket", "outline-arrow-left-to-bracket"),
								huh.NewOption("Outline Arrow Left", "outline-arrow-left"),
								huh.NewOption("Outline Arrow Right Alt", "outline-arrow-right-alt"),
								huh.NewOption("Outline Arrow Right To Bracket", "outline-arrow-right-to-bracket"),
								huh.NewOption("Outline Arrow Right", "outline-arrow-right"),
								huh.NewOption("Outline Arrow Sort Letters", "outline-arrow-sort-letters"),
								huh.NewOption("Outline Arrow Up Down", "outline-arrow-up-down"),
								huh.NewOption("Outline Arrow Up From Bracket", "outline-arrow-up-from-bracket"),
								huh.NewOption("Outline Arrow Up Right Down Left", "outline-arrow-up-right-down-left"),
								huh.NewOption("Outline Arrow Up Right From Square", "outline-arrow-up-right-from-square"),
								huh.NewOption("Outline Arrow Up", "outline-arrow-up"),
								huh.NewOption("Outline Arrows Repeat Count", "outline-arrows-repeat-count"),
								huh.NewOption("Outline Arrows Repeat", "outline-arrows-repeat"),
								huh.NewOption("Outline Atom", "outline-atom"),
								huh.NewOption("Outline Award", "outline-award"),
								huh.NewOption("Outline Backward Step", "outline-backward-step"),
								huh.NewOption("Outline Badge Check", "outline-badge-check"),
								huh.NewOption("Outline Ban", "outline-ban"),
								huh.NewOption("Outline Barcode", "outline-barcode"),
								huh.NewOption("Outline Bars From Left", "outline-bars-from-left"),
								huh.NewOption("Outline Bars", "outline-bars"),
								huh.NewOption("Outline Battery", "outline-battery"),
								huh.NewOption("Outline Bed", "outline-bed"),
								huh.NewOption("Outline Bell Active Alt", "outline-bell-active-alt"),
								huh.NewOption("Outline Bell Active", "outline-bell-active"),
								huh.NewOption("Outline Bell Ring", "outline-bell-ring"),
								huh.NewOption("Outline Bell", "outline-bell"),
								huh.NewOption("Outline Blender Phone", "outline-blender-phone"),
								huh.NewOption("Outline Book Open", "outline-book-open"),
								huh.NewOption("Outline Book", "outline-book"),
								huh.NewOption("Outline Bookmark", "outline-bookmark"),
								huh.NewOption("Outline Booth Curtain", "outline-booth-curtain"),
								huh.NewOption("Outline Brain", "outline-brain"),
								huh.NewOption("Outline Briefcase", "outline-briefcase"),
								huh.NewOption("Outline Bug", "outline-bug"),
								huh.NewOption("Outline Building", "outline-building"),
								huh.NewOption("Outline Bullhorn", "outline-bullhorn"),
								huh.NewOption("Outline Calendar Edit", "outline-calendar-edit"),
								huh.NewOption("Outline Calendar Month", "outline-calendar-month"),
								huh.NewOption("Outline Calendar Plus", "outline-calendar-plus"),
								huh.NewOption("Outline Calendar Week", "outline-calendar-week"),
								huh.NewOption("Outline Camera Photo", "outline-camera-photo"),
								huh.NewOption("Outline Caption", "outline-caption"),
								huh.NewOption("Outline Caret Down", "outline-caret-down"),
								huh.NewOption("Outline Caret Left", "outline-caret-left"),
								huh.NewOption("Outline Caret Right", "outline-caret-right"),
								huh.NewOption("Outline Caret Sort", "outline-caret-sort"),
								huh.NewOption("Outline Caret Up", "outline-caret-up"),
								huh.NewOption("Outline Cart Plus Alt", "outline-cart-plus-alt"),
								huh.NewOption("Outline Cart Plus", "outline-cart-plus"),
								huh.NewOption("Outline Cart", "outline-cart"),
								huh.NewOption("Outline Cash Register", "outline-cash-register"),
								huh.NewOption("Outline Cash", "outline-cash"),
								huh.NewOption("Outline Cell Attributes", "outline-cell-attributes"),
								huh.NewOption("Outline Chart Line Down", "outline-chart-line-down"),
								huh.NewOption("Outline Chart Line Up", "outline-chart-line-up"),
								huh.NewOption("Outline Chart Mixed Dollar", "outline-chart-mixed-dollar"),
								huh.NewOption("Outline Chart Mixed", "outline-chart-mixed"),
								huh.NewOption("Outline Chart Pie", "outline-chart-pie"),
								huh.NewOption("Outline Chart", "outline-chart"),
								huh.NewOption("Outline Check Circle", "outline-check-circle"),
								huh.NewOption("Outline Check Plus Circle", "outline-check-plus-circle"),
								huh.NewOption("Outline Check", "outline-check"),
								huh.NewOption("Outline Chevron Double Down", "outline-chevron-double-down"),
								huh.NewOption("Outline Chevron Double Left", "outline-chevron-double-left"),
								huh.NewOption("Outline Chevron Double Right", "outline-chevron-double-right"),
								huh.NewOption("Outline Chevron Double Up", "outline-chevron-double-up"),
								huh.NewOption("Outline Chevron Down", "outline-chevron-down"),
								huh.NewOption("Outline Chevron Left", "outline-chevron-left"),
								huh.NewOption("Outline Chevron Right", "outline-chevron-right"),
								huh.NewOption("Outline Chevron Sort", "outline-chevron-sort"),
								huh.NewOption("Outline Chevron Up", "outline-chevron-up"),
								huh.NewOption("Outline Circle Minus", "outline-circle-minus"),
								huh.NewOption("Outline Circle Pause", "outline-circle-pause"),
								huh.NewOption("Outline Circle Plus", "outline-circle-plus"),
								huh.NewOption("Outline Clapperboard Play", "outline-clapperboard-play"),
								huh.NewOption("Outline Clipboard Check", "outline-clipboard-check"),
								huh.NewOption("Outline Clipboard Clean", "outline-clipboard-clean"),
								huh.NewOption("Outline Clipboard List", "outline-clipboard-list"),
								huh.NewOption("Outline Clipboard", "outline-clipboard"),
								huh.NewOption("Outline Clock", "outline-clock"),
								huh.NewOption("Outline Close Circle", "outline-close-circle"),
								huh.NewOption("Outline Close", "outline-close"),
								huh.NewOption("Outline Cloud Arrow Up", "outline-cloud-arrow-up"),
								huh.NewOption("Outline Code Branch", "outline-code-branch"),
								huh.NewOption("Outline Code Fork", "outline-code-fork"),
								huh.NewOption("Outline Code Merge", "outline-code-merge"),
								huh.NewOption("Outline Code Pull Request", "outline-code-pull-request"),
								huh.NewOption("Outline Code", "outline-code"),
								huh.NewOption("Outline Cog", "outline-cog"),
								huh.NewOption("Outline Column", "outline-column"),
								huh.NewOption("Outline Command", "outline-command"),
								huh.NewOption("Outline Compress", "outline-compress"),
								huh.NewOption("Outline Computer Speaker", "outline-computer-speaker"),
								huh.NewOption("Outline Credit Card Plus Alt", "outline-credit-card-plus-alt"),
								huh.NewOption("Outline Credit Card Plus", "outline-credit-card-plus"),
								huh.NewOption("Outline Credit Card", "outline-credit-card"),
								huh.NewOption("Outline Database", "outline-database"),
								huh.NewOption("Outline Delete Column", "outline-delete-column"),
								huh.NewOption("Outline Delete Row", "outline-delete-row"),
								huh.NewOption("Outline Delete Table", "outline-delete-table"),
								huh.NewOption("Outline Desktop PC", "outline-desktop-pc"),
								huh.NewOption("Outline DNA", "outline-dna"),
								huh.NewOption("Outline Dollar", "outline-dollar"),
								huh.NewOption("Outline Dots Horizontal", "outline-dots-horizontal"),
								huh.NewOption("Outline Dots Vertical", "outline-dots-vertical"),
								huh.NewOption("Outline Download", "outline-download"),
								huh.NewOption("Outline Draw Square", "outline-draw-square"),
								huh.NewOption("Outline Edit", "outline-edit"),
								huh.NewOption("Outline Envelope Open", "outline-envelope-open"),
								huh.NewOption("Outline Envelope", "outline-envelope"),
								huh.NewOption("Outline Euro", "outline-euro"),
								huh.NewOption("Outline Exclamation Circle", "outline-exclamation-circle"),
								huh.NewOption("Outline Expand", "outline-expand"),
								huh.NewOption("Outline Eye Slash", "outline-eye-slash"),
								huh.NewOption("Outline Eye", "outline-eye"),
								huh.NewOption("Outline Face Explode", "outline-face-explode"),
								huh.NewOption("Outline Face Grin Stars", "outline-face-grin-stars"),
								huh.NewOption("Outline Face Grin", "outline-face-grin"),
								huh.NewOption("Outline Face Laugh", "outline-face-laugh"),
								huh.NewOption("Outline File Chart Bar", "outline-file-chart-bar"),
								huh.NewOption("Outline File Check", "outline-file-check"),
								huh.NewOption("Outline File Circle Plus", "outline-file-circle-plus"),
								huh.NewOption("Outline File Clone", "outline-file-clone"),
								huh.NewOption("Outline File Code", "outline-file-code"),
								huh.NewOption("Outline File Copy Alt", "outline-file-copy-alt"),
								huh.NewOption("Outline File Copy", "outline-file-copy"),
								huh.NewOption("Outline File Csv", "outline-file-csv"),
								huh.NewOption("Outline File Doc", "outline-file-doc"),
								huh.NewOption("Outline File Export", "outline-file-export"),
								huh.NewOption("Outline File Image", "outline-file-image"),
								huh.NewOption("Outline File Import", "outline-file-import"),
								huh.NewOption("Outline File Invoice", "outline-file-invoice"),
								huh.NewOption("Outline File Lines", "outline-file-lines"),
								huh.NewOption("Outline File Music", "outline-file-music"),
								huh.NewOption("Outline File Paste", "outline-file-paste"),
								huh.NewOption("Outline File Pdf", "outline-file-pdf"),
								huh.NewOption("Outline File Pen", "outline-file-pen"),
								huh.NewOption("Outline File Ppt", "outline-file-ppt"),
								huh.NewOption("Outline File Search", "outline-file-search"),
								huh.NewOption("Outline File Shield", "outline-file-shield"),
								huh.NewOption("Outline File Video", "outline-file-video"),
								huh.NewOption("Outline File Word", "outline-file-word"),
								huh.NewOption("Outline File Zip", "outline-file-zip"),
								huh.NewOption("Outline File", "outline-file"),
								huh.NewOption("Outline Filter Dollar", "outline-filter-dollar"),
								huh.NewOption("Outline Filter", "outline-filter"),
								huh.NewOption("Outline Fingerprint", "outline-fingerprint"),
								huh.NewOption("Outline Fire", "outline-fire"),
								huh.NewOption("Outline Fix Tables", "outline-fix-tables"),
								huh.NewOption("Outline Flag", "outline-flag"),
								huh.NewOption("Outline Floppy Disk Alt", "outline-floppy-disk-alt"),
								huh.NewOption("Outline Floppy Disk", "outline-floppy-disk"),
								huh.NewOption("Outline Folder Arrow Right", "outline-folder-arrow-right"),
								huh.NewOption("Outline Folder Duplicate", "outline-folder-duplicate"),
								huh.NewOption("Outline Folder Open", "outline-folder-open"),
								huh.NewOption("Outline Folder Plus", "outline-folder-plus"),
								huh.NewOption("Outline Folder", "outline-folder"),
								huh.NewOption("Outline Font Color", "outline-font-color"),
								huh.NewOption("Outline Font Family", "outline-font-family"),
								huh.NewOption("Outline Font Highlight", "outline-font-highlight"),
								huh.NewOption("Outline Forward Step", "outline-forward-step"),
								huh.NewOption("Outline Forward", "outline-forward"),
								huh.NewOption("Outline Gift Box", "outline-gift-box"),
								huh.NewOption("Outline Globe", "outline-globe"),
								huh.NewOption("Outline Go To Next Cell", "outline-go-to-next-cell"),
								huh.NewOption("Outline Go To Prev Cell", "outline-go-to-prev-cell"),
								huh.NewOption("Outline Grid Plus", "outline-grid-plus"),
								huh.NewOption("Outline Grid", "outline-grid"),
								huh.NewOption("Outline Hammer", "outline-hammer"),
								huh.NewOption("Outline Headphones", "outline-headphones"),
								huh.NewOption("Outline Heart", "outline-heart"),
								huh.NewOption("Outline Home", "outline-home"),
								huh.NewOption("Outline Horizontal Lines", "outline-horizontal-lines"),
								huh.NewOption("Outline Hourglass", "outline-hourglass"),
								huh.NewOption("Outline Image", "outline-image"),
								huh.NewOption("Outline Inbox Full", "outline-inbox-full"),
								huh.NewOption("Outline Inbox", "outline-inbox"),
								huh.NewOption("Outline Indent", "outline-indent"),
								huh.NewOption("Outline Info Circle", "outline-info-circle"),
								huh.NewOption("Outline Insert Row After", "outline-insert-row-after"),
								huh.NewOption("Outline Insert Row Before", "outline-insert-row-before"),
								huh.NewOption("Outline Insert Table Alt", "outline-insert-table-alt"),
								huh.NewOption("Outline Insert Table", "outline-insert-table"),
								huh.NewOption("Outline Keyboard", "outline-keyboard"),
								huh.NewOption("Outline Label", "outline-label"),
								huh.NewOption("Outline Landmark", "outline-landmark"),
								huh.NewOption("Outline Language", "outline-language"),
								huh.NewOption("Outline Layers", "outline-layers"),
								huh.NewOption("Outline Letter Bold", "outline-letter-bold"),
								huh.NewOption("Outline Letter Italic", "outline-letter-italic"),
								huh.NewOption("Outline Letter Underline", "outline-letter-underline"),
								huh.NewOption("Outline Life Saver", "outline-life-saver"),
								huh.NewOption("Outline Lightbulb", "outline-lightbulb"),
								huh.NewOption("Outline Link Break", "outline-link-break"),
								huh.NewOption("Outline Link", "outline-link"),
								huh.NewOption("Outline List Music", "outline-list-music"),
								huh.NewOption("Outline List", "outline-list"),
								huh.NewOption("Outline Lock Open", "outline-lock-open"),
								huh.NewOption("Outline Lock Time", "outline-lock-time"),
								huh.NewOption("Outline Lock", "outline-lock"),
								huh.NewOption("Outline Mail Box", "outline-mail-box"),
								huh.NewOption("Outline Map Pin Alt", "outline-map-pin-alt"),
								huh.NewOption("Outline Map Pin", "outline-map-pin"),
								huh.NewOption("Outline Merge Cells", "outline-merge-cells"),
								huh.NewOption("Outline Merge Or Split", "outline-merge-or-split"),
								huh.NewOption("Outline Message Caption", "outline-message-caption"),
								huh.NewOption("Outline Message Dots", "outline-message-dots"),
								huh.NewOption("Outline Messages", "outline-messages"),
								huh.NewOption("Outline Microphone Slash", "outline-microphone-slash"),
								huh.NewOption("Outline Microphone", "outline-microphone"),
								huh.NewOption("Outline Minimize", "outline-minimize"),
								huh.NewOption("Outline Minus", "outline-minus"),
								huh.NewOption("Outline Mobile Phone", "outline-mobile-phone"),
								huh.NewOption("Outline Moon", "outline-moon"),
								huh.NewOption("Outline Newspaper", "outline-newspaper"),
								huh.NewOption("Outline Objects Column", "outline-objects-column"),
								huh.NewOption("Outline Open Door", "outline-open-door"),
								huh.NewOption("Outline Ordered List", "outline-ordered-list"),
								huh.NewOption("Outline Outdent", "outline-outdent"),
								huh.NewOption("Outline Palette", "outline-palette"),
								huh.NewOption("Outline Paper Clip", "outline-paper-clip"),
								huh.NewOption("Outline Paper Plane", "outline-paper-plane"),
								huh.NewOption("Outline Paragraph", "outline-paragraph"),
								huh.NewOption("Outline Pause", "outline-pause"),
								huh.NewOption("Outline Pen Nib", "outline-pen-nib"),
								huh.NewOption("Outline Pen", "outline-pen"),
								huh.NewOption("Outline Phone Hangup", "outline-phone-hangup"),
								huh.NewOption("Outline Phone", "outline-phone"),
								huh.NewOption("Outline Play", "outline-play"),
								huh.NewOption("Outline Plus", "outline-plus"),
								huh.NewOption("Outline Printer", "outline-printer"),
								huh.NewOption("Outline Profile Card", "outline-profile-card"),
								huh.NewOption("Outline QR Code", "outline-qr-code"),
								huh.NewOption("Outline Question Circle", "outline-question-circle"),
								huh.NewOption("Outline Quote", "outline-quote"),
								huh.NewOption("Outline Receipt", "outline-receipt"),
								huh.NewOption("Outline Rectangle List", "outline-rectangle-list"),
								huh.NewOption("Outline Redo", "outline-redo"),
								huh.NewOption("Outline Refresh", "outline-refresh"),
								huh.NewOption("Outline Reply All", "outline-reply-all"),
								huh.NewOption("Outline Reply", "outline-reply"),
								huh.NewOption("Outline Restore Window", "outline-restore-window"),
								huh.NewOption("Outline Rocket", "outline-rocket"),
								huh.NewOption("Outline Ruler Combined", "outline-ruler-combined"),
								huh.NewOption("Outline Sale Percent", "outline-sale-percent"),
								huh.NewOption("Outline Scale Balanced", "outline-scale-balanced"),
								huh.NewOption("Outline Search", "outline-search"),
								huh.NewOption("Outline Server", "outline-server"),
								huh.NewOption("Outline Share All", "outline-share-all"),
								huh.NewOption("Outline Share Nodes", "outline-share-nodes"),
								huh.NewOption("Outline Shield Check", "outline-shield-check"),
								huh.NewOption("Outline Shield", "outline-shield"),
								huh.NewOption("Outline Shopping Bag", "outline-shopping-bag"),
								huh.NewOption("Outline Shuffle", "outline-shuffle"),
								huh.NewOption("Outline Sort Horizontal", "outline-sort-horizontal"),
								huh.NewOption("Outline Sort", "outline-sort"),
								huh.NewOption("Outline Split Cells", "outline-split-cells"),
								huh.NewOption("Outline Star Half Stroke", "outline-star-half-stroke"),
								huh.NewOption("Outline Star Half", "outline-star-half"),
								huh.NewOption("Outline Star", "outline-star"),
								huh.NewOption("Outline Stop", "outline-stop"),
								huh.NewOption("Outline Store", "outline-store"),
								huh.NewOption("Outline Subscript", "outline-subscript"),
								huh.NewOption("Outline Sun", "outline-sun"),
								huh.NewOption("Outline Superscript", "outline-superscript"),
								huh.NewOption("Outline Swatchbook", "outline-swatchbook"),
								huh.NewOption("Outline T Shirt", "outline-t-shirt"),
								huh.NewOption("Outline Table Column", "outline-table-column"),
								huh.NewOption("Outline Table Row", "outline-table-row"),
								huh.NewOption("Outline Tablet", "outline-tablet"),
								huh.NewOption("Outline Tag", "outline-tag"),
								huh.NewOption("Outline Teddy Bear", "outline-teddy-bear"),
								huh.NewOption("Outline Terminal", "outline-terminal"),
								huh.NewOption("Outline Text Size", "outline-text-size"),
								huh.NewOption("Outline Text Slash", "outline-text-slash"),
								huh.NewOption("Outline Text Underline", "outline-text-underline"),
								huh.NewOption("Outline Thumbs Down", "outline-thumbs-down"),
								huh.NewOption("Outline Thumbs Up", "outline-thumbs-up"),
								huh.NewOption("Outline Thumbtack", "outline-thumbtack"),
								huh.NewOption("Outline Ticket", "outline-ticket"),
								huh.NewOption("Outline Toggle Header Cell", "outline-toggle-header-cell"),
								huh.NewOption("Outline Toggle Header Column", "outline-toggle-header-column"),
								huh.NewOption("Outline Toggle Header Row", "outline-toggle-header-row"),
								huh.NewOption("Outline Tools", "outline-tools"),
								huh.NewOption("Outline Tracking", "outline-tracking"),
								huh.NewOption("Outline Trash Bin", "outline-trash-bin"),
								huh.NewOption("Outline Truck Clock", "outline-truck-clock"),
								huh.NewOption("Outline Truck", "outline-truck"),
								huh.NewOption("Outline Undo", "outline-undo"),
								huh.NewOption("Outline Upload", "outline-upload"),
								huh.NewOption("Outline User Add", "outline-user-add"),
								huh.NewOption("Outline User Circle", "outline-user-circle"),
								huh.NewOption("Outline User Edit", "outline-user-edit"),
								huh.NewOption("Outline User Headset", "outline-user-headset"),
								huh.NewOption("Outline User Remove", "outline-user-remove"),
								huh.NewOption("Outline User Settings", "outline-user-settings"),
								huh.NewOption("Outline User", "outline-user"),
								huh.NewOption("Outline Users Group", "outline-users-group"),
								huh.NewOption("Outline Users", "outline-users"),
								huh.NewOption("Outline Video Camera", "outline-video-camera"),
								huh.NewOption("Outline Volume Down", "outline-volume-down"),
								huh.NewOption("Outline Volume Mute", "outline-volume-mute"),
								huh.NewOption("Outline Volume Up", "outline-volume-up"),
								huh.NewOption("Outline Wallet", "outline-wallet"),
								huh.NewOption("Outline Wand Magic Sparkles", "outline-wand-magic-sparkles"),
								huh.NewOption("Outline Window", "outline-window"),
								huh.NewOption("Outline Zoom In", "outline-zoom-in"),
								huh.NewOption("Outline Zoom Out", "outline-zoom-out"),
								huh.NewOption("Solid X", "solid-x"),
								huh.NewOption("Solid Address Book", "solid-address-book"),
								huh.NewOption("Solid Adjustments Horizontal", "solid-adjustments-horizontal"),
								huh.NewOption("Solid Adjustments Vertical", "solid-adjustments-vertical"),
								huh.NewOption("Solid Annotation", "solid-annotation"),
								huh.NewOption("Solid Apple", "solid-apple"),
								huh.NewOption("Solid Archive Arrow Down", "solid-archive-arrow-down"),
								huh.NewOption("Solid Archive", "solid-archive"),
								huh.NewOption("Solid Arrow Right Alt", "solid-arrow-right-alt"),
								huh.NewOption("Solid Arrow Up Right From Square", "solid-arrow-up-right-from-square"),
								huh.NewOption("Solid Award", "solid-award"),
								huh.NewOption("Solid Aws", "solid-aws"),
								huh.NewOption("Solid Backward Step", "solid-backward-step"),
								huh.NewOption("Solid Badge Check", "solid-badge-check"),
								huh.NewOption("Solid Battery", "solid-battery"),
								huh.NewOption("Solid Bed", "solid-bed"),
								huh.NewOption("Solid Bell Active Alt", "solid-bell-active-alt"),
								huh.NewOption("Solid Bell Active", "solid-bell-active"),
								huh.NewOption("Solid Bell Ring", "solid-bell-ring"),
								huh.NewOption("Solid Bell", "solid-bell"),
								huh.NewOption("Solid Bitcoin", "solid-bitcoin"),
								huh.NewOption("Solid Blender Phone", "solid-blender-phone"),
								huh.NewOption("Solid Book Open", "solid-book-open"),
								huh.NewOption("Solid Book", "solid-book"),
								huh.NewOption("Solid Bookmark", "solid-bookmark"),
								huh.NewOption("Solid Booth Curtain", "solid-booth-curtain"),
								huh.NewOption("Solid Brain", "solid-brain"),
								huh.NewOption("Solid Briefcase", "solid-briefcase"),
								huh.NewOption("Solid Bug", "solid-bug"),
								huh.NewOption("Solid Building", "solid-building"),
								huh.NewOption("Solid Bullhorn", "solid-bullhorn"),
								huh.NewOption("Solid Calendar Edit", "solid-calendar-edit"),
								huh.NewOption("Solid Calendar Month", "solid-calendar-month"),
								huh.NewOption("Solid Calendar Plus", "solid-calendar-plus"),
								huh.NewOption("Solid Calendar Week", "solid-calendar-week"),
								huh.NewOption("Solid Camera Photo", "solid-camera-photo"),
								huh.NewOption("Solid Caption", "solid-caption"),
								huh.NewOption("Solid Caret Down", "solid-caret-down"),
								huh.NewOption("Solid Caret Left", "solid-caret-left"),
								huh.NewOption("Solid Caret Right", "solid-caret-right"),
								huh.NewOption("Solid Caret Sort", "solid-caret-sort"),
								huh.NewOption("Solid Caret Up", "solid-caret-up"),
								huh.NewOption("Solid Cart Plus Alt", "solid-cart-plus-alt"),
								huh.NewOption("Solid Cart Plus", "solid-cart-plus"),
								huh.NewOption("Solid Cart", "solid-cart"),
								huh.NewOption("Solid Cash Register", "solid-cash-register"),
								huh.NewOption("Solid Cash", "solid-cash"),
								huh.NewOption("Solid Chart Mixed Dollar", "solid-chart-mixed-dollar"),
								huh.NewOption("Solid Chart Pie", "solid-chart-pie"),
								huh.NewOption("Solid Check Circle", "solid-check-circle"),
								huh.NewOption("Solid Check Plus Circle", "solid-check-plus-circle"),
								huh.NewOption("Solid Circle Minus", "solid-circle-minus"),
								huh.NewOption("Solid Circle Pause", "solid-circle-pause"),
								huh.NewOption("Solid Circle Plus", "solid-circle-plus"),
								huh.NewOption("Solid Clapperboard Play", "solid-clapperboard-play"),
								huh.NewOption("Solid Clipboard Check", "solid-clipboard-check"),
								huh.NewOption("Solid Clipboard Clean", "solid-clipboard-clean"),
								huh.NewOption("Solid Clipboard List", "solid-clipboard-list"),
								huh.NewOption("Solid Clipboard", "solid-clipboard"),
								huh.NewOption("Solid Clock", "solid-clock"),
								huh.NewOption("Solid Close Circle", "solid-close-circle"),
								huh.NewOption("Solid Cloud Arrow Up", "solid-cloud-arrow-up"),
								huh.NewOption("Solid Code Branch", "solid-code-branch"),
								huh.NewOption("Solid Code Fork", "solid-code-fork"),
								huh.NewOption("Solid Code Merge", "solid-code-merge"),
								huh.NewOption("Solid Code Pull Request", "solid-code-pull-request"),
								huh.NewOption("Solid Cog", "solid-cog"),
								huh.NewOption("Solid Column", "solid-column"),
								huh.NewOption("Solid Computer Speaker", "solid-computer-speaker"),
								huh.NewOption("Solid Credit Card Plus Alt", "solid-credit-card-plus-alt"),
								huh.NewOption("Solid Credit Card Plus", "solid-credit-card-plus"),
								huh.NewOption("Solid Credit Card", "solid-credit-card"),
								huh.NewOption("Solid Css", "solid-css"),
								huh.NewOption("Solid Database", "solid-database"),
								huh.NewOption("Solid Desktop Pc", "solid-desktop-pc"),
								huh.NewOption("Solid Discord", "solid-discord"),
								huh.NewOption("Solid Download", "solid-download"),
								huh.NewOption("Solid Draw Square", "solid-draw-square"),
								huh.NewOption("Solid Dribbble", "solid-dribbble"),
								huh.NewOption("Solid Dropbox", "solid-dropbox"),
								huh.NewOption("Solid Edit", "solid-edit"),
								huh.NewOption("Solid Envelope Open", "solid-envelope-open"),
								huh.NewOption("Solid Envelope", "solid-envelope"),
								huh.NewOption("Solid Exclamation Circle", "solid-exclamation-circle"),
								huh.NewOption("Solid Eye Slash", "solid-eye-slash"),
								huh.NewOption("Solid Eye", "solid-eye"),
								huh.NewOption("Solid Face Explode", "solid-face-explode"),
								huh.NewOption("Solid Face Grin Stars", "solid-face-grin-stars"),
								huh.NewOption("Solid Face Grin", "solid-face-grin"),
								huh.NewOption("Solid Face Laugh", "solid-face-laugh"),
								huh.NewOption("Solid Facebook", "solid-facebook"),
								huh.NewOption("Solid File Chart Bar", "solid-file-chart-bar"),
								huh.NewOption("Solid File Check", "solid-file-check"),
								huh.NewOption("Solid File Circle Plus", "solid-file-circle-plus"),
								huh.NewOption("Solid File Clone", "solid-file-clone"),
								huh.NewOption("Solid File Code", "solid-file-code"),
								huh.NewOption("Solid File Copy Alt", "solid-file-copy-alt"),
								huh.NewOption("Solid File Copy", "solid-file-copy"),
								huh.NewOption("Solid File Csv", "solid-file-csv"),
								huh.NewOption("Solid File Doc", "solid-file-doc"),
								huh.NewOption("Solid File Export", "solid-file-export"),
								huh.NewOption("Solid File Image", "solid-file-image"),
								huh.NewOption("Solid File Import", "solid-file-import"),
								huh.NewOption("Solid File Invoice", "solid-file-invoice"),
								huh.NewOption("Solid File Lines", "solid-file-lines"),
								huh.NewOption("Solid File Music", "solid-file-music"),
								huh.NewOption("Solid File Paste", "solid-file-paste"),
								huh.NewOption("Solid File Pdf", "solid-file-pdf"),
								huh.NewOption("Solid File Pen", "solid-file-pen"),
								huh.NewOption("Solid File Ppt", "solid-file-ppt"),
								huh.NewOption("Solid File Search", "solid-file-search"),
								huh.NewOption("Solid File Shield", "solid-file-shield"),
								huh.NewOption("Solid File Video", "solid-file-video"),
								huh.NewOption("Solid File Word", "solid-file-word"),
								huh.NewOption("Solid File Zip", "solid-file-zip"),
								huh.NewOption("Solid File", "solid-file"),
								huh.NewOption("Solid Filter Dollar", "solid-filter-dollar"),
								huh.NewOption("Solid Filter", "solid-filter"),
								huh.NewOption("Solid Fire", "solid-fire"),
								huh.NewOption("Solid Flag", "solid-flag"),
								huh.NewOption("Solid Floppy Disk Alt", "solid-floppy-disk-alt"),
								huh.NewOption("Solid Floppy Disk", "solid-floppy-disk"),
								huh.NewOption("Solid Flowbite", "solid-flowbite"),
								huh.NewOption("Solid Folder Arrow Right", "solid-folder-arrow-right"),
								huh.NewOption("Solid Folder Duplicate", "solid-folder-duplicate"),
								huh.NewOption("Solid Folder Open", "solid-folder-open"),
								huh.NewOption("Solid Folder Plus", "solid-folder-plus"),
								huh.NewOption("Solid Folder", "solid-folder"),
								huh.NewOption("Solid Font Color Alt", "solid-font-color-alt"),
								huh.NewOption("Solid Forward Step", "solid-forward-step"),
								huh.NewOption("Solid Forward", "solid-forward"),
								huh.NewOption("Solid Gift Box", "solid-gift-box"),
								huh.NewOption("Solid Github", "solid-github"),
								huh.NewOption("Solid Gitlab", "solid-gitlab"),
								huh.NewOption("Solid Globe", "solid-globe"),
								huh.NewOption("Solid Google", "solid-google"),
								huh.NewOption("Solid Grid Plus", "solid-grid-plus"),
								huh.NewOption("Solid Grid", "solid-grid"),
								huh.NewOption("Solid Hammer", "solid-hammer"),
								huh.NewOption("Solid Headphones", "solid-headphones"),
								huh.NewOption("Solid Heart", "solid-heart"),
								huh.NewOption("Solid Home", "solid-home"),
								huh.NewOption("Solid Hourglass", "solid-hourglass"),
								huh.NewOption("Solid Html", "solid-html"),
								huh.NewOption("Solid Image", "solid-image"),
								huh.NewOption("Solid Inbox Full", "solid-inbox-full"),
								huh.NewOption("Solid Inbox", "solid-inbox"),
								huh.NewOption("Solid Indent", "solid-indent"),
								huh.NewOption("Solid Info Circle", "solid-info-circle"),
								huh.NewOption("Solid Instagram", "solid-instagram"),
								huh.NewOption("Solid Keyboard", "solid-keyboard"),
								huh.NewOption("Solid Label", "solid-label"),
								huh.NewOption("Solid Landmark", "solid-landmark"),
								huh.NewOption("Solid Laravel", "solid-laravel"),
								huh.NewOption("Solid Layers", "solid-layers"),
								huh.NewOption("Solid Life Saver", "solid-life-saver"),
								huh.NewOption("Solid Lightbulb", "solid-lightbulb"),
								huh.NewOption("Solid Linkedin", "solid-linkedin"),
								huh.NewOption("Solid List Music", "solid-list-music"),
								huh.NewOption("Solid Lock Open", "solid-lock-open"),
								huh.NewOption("Solid Lock Time", "solid-lock-time"),
								huh.NewOption("Solid Lock", "solid-lock"),
								huh.NewOption("Solid Mail Box", "solid-mail-box"),
								huh.NewOption("Solid Map Pin Alt", "solid-map-pin-alt"),
								huh.NewOption("Solid Map Pin", "solid-map-pin"),
								huh.NewOption("Solid Mastercard", "solid-mastercard"),
								huh.NewOption("Solid Message Caption", "solid-message-caption"),
								huh.NewOption("Solid Message Dots", "solid-message-dots"),
								huh.NewOption("Solid Messages", "solid-messages"),
								huh.NewOption("Solid Microphone Slash", "solid-microphone-slash"),
								huh.NewOption("Solid Microphone", "solid-microphone"),
								huh.NewOption("Solid Mobile Phone", "solid-mobile-phone"),
								huh.NewOption("Solid Mongo DB", "solid-mongo-db"),
								huh.NewOption("Solid Moon", "solid-moon"),
								huh.NewOption("Solid Newspaper", "solid-newspaper"),
								huh.NewOption("Solid Npm", "solid-npm"),
								huh.NewOption("Solid Objects Column", "solid-objects-column"),
								huh.NewOption("Solid Open Door", "solid-open-door"),
								huh.NewOption("Solid Outdent", "solid-outdent"),
								huh.NewOption("Solid Palette", "solid-palette"),
								huh.NewOption("Solid Paper Plane", "solid-paper-plane"),
								huh.NewOption("Solid Paragraph", "solid-paragraph"),
								huh.NewOption("Solid Pause", "solid-pause"),
								huh.NewOption("Solid Pen Nib", "solid-pen-nib"),
								huh.NewOption("Solid Pen", "solid-pen"),
								huh.NewOption("Solid Phone Hangup", "solid-phone-hangup"),
								huh.NewOption("Solid Phone", "solid-phone"),
								huh.NewOption("Solid Play", "solid-play"),
								huh.NewOption("Solid Printer", "solid-printer"),
								huh.NewOption("Solid Profile Card", "solid-profile-card"),
								huh.NewOption("Solid Question Circle", "solid-question-circle"),
								huh.NewOption("Solid Quote", "solid-quote"),
								huh.NewOption("Solid React", "solid-react"),
								huh.NewOption("Solid Receipt", "solid-receipt"),
								huh.NewOption("Solid Rectangle List", "solid-rectangle-list"),
								huh.NewOption("Solid Reddit", "solid-reddit"),
								huh.NewOption("Solid Reply All", "solid-reply-all"),
								huh.NewOption("Solid Reply", "solid-reply"),
								huh.NewOption("Solid Rocket", "solid-rocket"),
								huh.NewOption("Solid Sale Percent", "solid-sale-percent"),
								huh.NewOption("Solid Scale Balanced", "solid-scale-balanced"),
								huh.NewOption("Solid Search", "solid-search"),
								huh.NewOption("Solid Server", "solid-server"),
								huh.NewOption("Solid Share All", "solid-share-all"),
								huh.NewOption("Solid Share Nodes", "solid-share-nodes"),
								huh.NewOption("Solid Shield Check", "solid-shield-check"),
								huh.NewOption("Solid Shield", "solid-shield"),
								huh.NewOption("Solid Shopping Bag", "solid-shopping-bag"),
								huh.NewOption("Solid Stackoverflow", "solid-stackoverflow"),
								huh.NewOption("Solid Star Half Stroke", "solid-star-half-stroke"),
								huh.NewOption("Solid Star Half", "solid-star-half"),
								huh.NewOption("Solid Star", "solid-star"),
								huh.NewOption("Solid Stop", "solid-stop"),
								huh.NewOption("Solid Store", "solid-store"),
								huh.NewOption("Solid Sun", "solid-sun"),
								huh.NewOption("Solid Swatchbook", "solid-swatchbook"),
								huh.NewOption("Solid T Shirt", "solid-t-shirt"),
								huh.NewOption("Solid Table Column", "solid-table-column"),
								huh.NewOption("Solid Table Row", "solid-table-row"),
								huh.NewOption("Solid Tablet", "solid-tablet"),
								huh.NewOption("Solid Tag", "solid-tag"),
								huh.NewOption("Solid Tailwind", "solid-tailwind"),
								huh.NewOption("Solid Teddy Bear", "solid-teddy-bear"),
								huh.NewOption("Solid Terminal", "solid-terminal"),
								huh.NewOption("Solid Thumbs Down", "solid-thumbs-down"),
								huh.NewOption("Solid Thumbs Up", "solid-thumbs-up"),
								huh.NewOption("Solid Thumbtack", "solid-thumbtack"),
								huh.NewOption("Solid Ticket", "solid-ticket"),
								huh.NewOption("Solid Tracking", "solid-tracking"),
								huh.NewOption("Solid Trash Bin", "solid-trash-bin"),
								huh.NewOption("Solid Truck Clock", "solid-truck-clock"),
								huh.NewOption("Solid Truck", "solid-truck"),
								huh.NewOption("Solid Twitter", "solid-twitter"),
								huh.NewOption("Solid Upload", "solid-upload"),
								huh.NewOption("Solid User Add", "solid-user-add"),
								huh.NewOption("Solid User Circle", "solid-user-circle"),
								huh.NewOption("Solid User Edit", "solid-user-edit"),
								huh.NewOption("Solid User Headset", "solid-user-headset"),
								huh.NewOption("Solid User Remove", "solid-user-remove"),
								huh.NewOption("Solid User Settings", "solid-user-settings"),
								huh.NewOption("Solid User", "solid-user"),
								huh.NewOption("Solid Users Group", "solid-users-group"),
								huh.NewOption("Solid Users", "solid-users"),
								huh.NewOption("Solid Video Camera", "solid-video-camera"),
								huh.NewOption("Solid Visa", "solid-visa"),
								huh.NewOption("Solid Volume Down", "solid-volume-down"),
								huh.NewOption("Solid Volume Mute", "solid-volume-mute"),
								huh.NewOption("Solid Volume Up", "solid-volume-up"),
								huh.NewOption("Solid Vue", "solid-vue"),
								huh.NewOption("Solid Wallet", "solid-wallet"),
								huh.NewOption("Solid Wand Magic Sparkles", "solid-wand-magic-sparkles"),
								huh.NewOption("Solid Whatsapp", "solid-whatsapp"),
								huh.NewOption("Solid Window Restore", "solid-window-restore"),
								huh.NewOption("Solid Window", "solid-window"),
								huh.NewOption("Solid Windows", "solid-windows"),
								huh.NewOption("Solid Youtube", "solid-youtube"),
								huh.NewOption("Solid Zoom In", "solid-zoom-in"),
								huh.NewOption("Solid Zoom Out", "solid-zoom-out"),
							).
							Value(&i.feature.Icon),
					).WithShowHelp(false).WithHeight(m.Parent.height - 3).WithWidth(m.Parent.width),
				)

				featureEditModel := &FeatureEditModel{
					Feature:       i.feature,
					Block:         m.Block,
					Form:          form,
					NavigationCtx: m.NavigationCtx,
					Parent:        m.Parent,
				}
				m.Parent.ModelStack.Push(featureEditModel)
				return m.Parent.ModelStack.Current(), m.Parent.ModelStack.Current().Init()
			}
		}
		if msg.String() == "a" {
			*m.Features = append(*m.Features, Feature{
				Heading: "Heading",
				Summary: "Summary",
			})
			newFeature := &(*m.Features)[len(*m.Features)-1]

			m.Block.SetFeatures(*m.Features)

			featureItem := FeatureListItem{feature: newFeature}
			m.List.InsertItem(len(m.List.Items()), featureItem)

			m.Parent.LandingPage.Write()
			form := huh.NewForm(
				huh.NewGroup(
					huh.NewInput().
						Key("heading").
						Title("Heading").
						Value(&newFeature.Heading),
					huh.NewText().
						Key("summary").
						Title("Summary").
						Value(&newFeature.Summary),
				).WithShowHelp(false),
			)

			m.NavigationCtx.Push("New Feature")
			featureEditModel := &FeatureEditModel{
				Feature:       newFeature,
				Block:         m.Block,
				Form:          form,
				NavigationCtx: m.NavigationCtx,
				Parent:        m.Parent,
			}
			m.Parent.ModelStack.Push(featureEditModel)
			return m.Parent.ModelStack.Current(), m.Parent.ModelStack.Current().Init()
		}
		if msg.String() == "x" {
			selectedIndex := m.List.Index()
			// panic(fmt.Sprintf("Selected index: %d, Features length: %d", selectedIndex, len(*m.Features)))

			if selectedIndex >= 0 && selectedIndex < len(*m.Features) {
				// Create new slice without selected item
				newFeatures := make([]Feature, 0, len(*m.Features)-1)
				newFeatures = append(newFeatures, (*m.Features)[:selectedIndex]...)
				newFeatures = append(newFeatures, (*m.Features)[selectedIndex+1:]...)
				*m.Features = newFeatures

				// Update block and list
				m.Block.SetFeatures(*m.Features)
				m.List.RemoveItem(selectedIndex)
				m.Parent.LandingPage.Write()
			}
		}
		if msg.String() == "i" {
			m.NavigationCtx.Push("Import Features")
			m.Parent.ModelStack.Push(CreateFeatureImportModelFromMainModel(m.Parent, m.Block, m.Features, &m.List))
			return m.Parent.ModelStack.Current(), m.Parent.ModelStack.Current().Init()
		}

	case tea.WindowSizeMsg:
		h, v := lipgloss.NewStyle().Margin(2, 2).GetFrameSize()
		m.List.SetSize(msg.Width-h, msg.Height-v)
	}

	var cmd tea.Cmd
	m.List, cmd = m.List.Update(msg)
	return m, cmd
}

func (m *FeatureListModel) View() string {
	breadcrumb := m.NavigationCtx.Path[0]
	for i := 1; i < len(m.NavigationCtx.Path); i++ {
		breadcrumb += " > " + m.NavigationCtx.Path[i]
	}
	return breadcrumb + "\n\n" + m.List.View()
}
