package modular

func AllBlocks() []BlockInterface {
	return []BlockInterface{
		&HeroSectionsDefault{
			Type:        "HeroSectionsDefault",
			HideFromNav: false,
			Library:     "FlowBite",
			Heading:     "Hero Section",
			Subheading:  "We are a team of developers and designers who are passionate about creating beautiful and functional websites.",
			Left: SideJustCTA{
				CTA: CTA{
					Text: "Learn More Today",
					URL:  "#",
				},
			},
			Right: SideJustCTA{
				CTA: CTA{
					Text: "Learn More Today",
					URL:  "#",
				},
			},
		},
		&MarketingHeroCoverImageWithCtas{
			Type:        "MarketingHeroCoverImageWithCtas",
			HideFromNav: true,
			Heading:     "Discover new product and best possibilities",
			Subheading:  "Here at Flowbite we focus on markets where technology, innovation, and capital can unlock long-term value and drive economic growth.",
			Left: Side{
				Heading:    "28 November 2021",
				Subheading: "Join us at FlowBite 2021 to understand what's next as the global tech and startup ecosystem, rethinks the future of everything.",
				CTA: CTA{
					Text: "Conference",
					URL:  "#",
				},
			},
			Right: Side{
				Heading:    "25+ top notch speakers",
				Subheading: "Here you will find keynote speakers, who all are able to talk about Recruiting. Click on the individual keynote speakers and read more about them and their keynotes.",
				CTA: CTA{
					Text: "View list",
					URL:  "#",
				},
			},
			Image: Image{
				URL: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/hero/conference-speaker.jpg",
			},
		},
		&FeatureSection{
			Identifier:  "feature_section_cta_list_1",
			Type:        "FeatureSection",
			Library:     "FlowBite",
			View:        "cta-list",
			Heading:     "The most trusted cryptocurrency platform",
			HideFromNav: false,
			Subheading:  "Here are a few reasons why you should choose Flowbite",
			Features: []Feature{
				{
					Heading: "Secure storage",
					Summary: "We store the vast majority of the digital assets in secure offline storage.",
					Icon:    "solid-wand-magic-sparkles",
				},
				{
					Heading: "Insurance",
					Summary: "Flowbite maintains crypto insurance and all USD cash balances are covered.",
					Icon:    "solid-award",
				},
				{
					Heading: "Best Practices",
					Summary: "Flowbite marketplace supports a variety of the most popular digital currencies.",
					Icon:    "solid-badge-check",
				},
			},
		},
		&FeatureSection{
			Identifier:  "feature_section_cta_list_2",
			Type:        "FeatureSection",
			Library:     "FlowBite",
			View:        "cta-list",
			Heading:     "The most trusted cryptocurrency platform",
			HideFromNav: false,
			Subheading:  "Here are a few reasons why you should choose Flowbite",
			Features: []Feature{
				{
					Heading: "Secure storage",
					Summary: "We store the vast majority of the digital assets in secure offline storage.",
					Icon:    "solid-wand-magic-sparkles",
				},
				{
					Heading: "Insurance",
					Summary: "Flowbite maintains crypto insurance and all USD cash balances are covered.",
					Icon:    "solid-award",
				},
				{
					Heading: "Best Practices",
					Summary: "Flowbite marketplace supports a variety of the most popular digital currencies.",
					Icon:    "solid-badge-check",
				},
			},
		},
		&FeatureSection{
			Type:        "FeatureSection",
			Library:     "FlowBite",
			Heading:     "Designed for business teams like yours",
			HideFromNav: false,
			Subheading:  "Here are a few reasons why you should choose Flowbite",
			View:        "icons",
			Features: []Feature{
				{
					Heading: "Just the right balance for growth",
					Summary: "Enterprise tools cost more, are difficult to use, and take longer to implement. According to G2, Flowbite is the easiest-to-use tool, with the fastest time to ROI.",
					Icon:    "solid-clock",
				},
				{
					Heading: "Just the right balance for growth",
					Summary: "Enterprise tools cost more, are difficult to use, and take longer to implement. According to G2, Flowbite is the easiest-to-use tool, with the fastest time to ROI.",
					Icon:    "solid-heart",
				},
			},
		},
		&FeatureSection{
			Type:        "FeatureSection",
			Library:     "FlowBite",
			HideFromNav: false,
			Heading:     "Secure platform, secure data",
			Subheading:  "Here are a few reasons why you should choose Flowbite",
			View:        "card-list",
			Features: []Feature{
				{
					Heading: "Marketing",
					Summary: "Plan it, create it, launch it. Collaborate seamlessly with all the organization and hit your marketing goals every month with our marketing plan.",
				},
				{
					Heading: "Legal",
					Summary: "Protect your organization, devices and stay compliant with our structured workflows and custom permissions made for you.",
				},
				{
					Heading: "Business Automation",
					Summary: "Auto-assign tasks, send Slack messages, and much more. Now power up with hundreds of new templates to help you get started.",
				},
				{
					Heading: "Finance",
					Summary: "Audit-proof software built for critical financial operations like month-end close and quarterly budgeting.",
				},
				{
					Heading: "Enterprise Design",
					Summary: "Craft beautiful, delightful experiences for both marketing and product with real cross-company collaboration.",
				},
				{
					Heading: "Operations",
					Summary: "Keep your company's lights on with customizable, iterative, and structured workflows built for all efficient teams and individual.",
				},
			},
		},
		&FeatureSectionsAlternate{
			Type:        "FeatureSectionsAlternate",
			HideFromNav: false,
			Library:     "FlowBite",
			Left: BulletList{
				Heading:    "Feature Sections Alternate",
				Subheading: "Feature Sections Alternate",
				Footer:     "Footer",
				Sentiment:  "negative",
				Feature1:   "Feature 1",
				Feature2:   "Feature 2",
				Feature3:   "Feature 3",
				Feature4:   "Feature 4",
				Feature5:   "Feature 5",
				Feature6:   "Feature 6",
			},
			Right: BulletList{
				Heading:    "Feature Sections Alternate",
				Subheading: "Feature Sections Alternate",
				Footer:     "Footer",
				Sentiment:  "positive",
				Feature1:   "Feature 1",
				Feature2:   "Feature 2",
				Feature3:   "Feature 3",
				Feature4:   "Feature 4",
				Feature5:   "Feature 5",
				Feature6:   "Feature 6",
			},
		},
		&PricingTable{
			Type:          "PricingTable",
			HideFromNav:   false,
			Library:       "FlowBite",
			Heading:       "Pricing Plans",
			Subheading:    "Flexible pricing for all teams and budgets.",
			ProductLineID: "observability_workshop_1",
		},
		&ContactFormsDefault{
			Type:        "ContactFormsDefault",
			HideFromNav: false,
			Library:     "FlowBite",
			Heading:     "Contact us",
			Subheading:  "We are a team of developers and designers who are passionate about creating beautiful and functional websites.",
		},
		&TestimonialSectionsBlockquote{
			Identifier:  "testimonial_sections_blockquote_1",
			Type:        "TestimonialSectionsBlockquote",
			HideFromNav: false,
			Library:     "FlowBite",
			Testimonial: Testimonial{
				Content: "We are a team of developers and designers who are passionate about creating beautiful and functional websites.",
				Author: Author{
					Name:     "Micheal Gough",
					Title:    "CEO at Google",
					ImageSrc: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/michael-gouch.png",
				},
			},
		},
		&TestimonialSectionsBlockquote{
			Identifier:  "testimonial_sections_blockquote_2",
			Type:        "TestimonialSectionsBlockquote",
			HideFromNav: false,
			Library:     "FlowBite",
			Testimonial: Testimonial{
				Content: "We are a team of developers and designers who are passionate about creating beautiful and functional websites.",
				Author: Author{
					Name:     "Micheal Gough",
					Title:    "CEO at Google",
					ImageSrc: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/michael-gouch.png",
				},
			},
		},
		&SocialProofCardStatistics{
			Identifier:  "social_proof_card_statistics_negative",
			Type:        "SocialProofCardStatistics",
			HideFromNav: false,
			Library:     "FlowBite",
			Heading:     "Social Proof Card Statistics",
			Subheading:  "We are a team of developers and designers who are passionate about creating beautiful and functional websites.",
			Note:        "Results based on a composite organization of 1,800 developers using GitHub over three years.",
			Sentiment:   "negative",
			Statistics: Statistics{
				Left: Statistic{
					Value:       "40%",
					Title:       "Reduction",
					Description: "in developer onboarding time",
				},
				Center: Statistic{
					Value:       "469%",
					Title:       "Return on investment",
					Description: "over 3 years",
				},
				Right: Statistic{
					Value:       "60+",
					Title:       "Minutes saved",
					Description: "per developer, per day",
				},
			},
		},
		&SocialProofCardStatistics{
			Identifier:  "social_proof_card_statistics_positive",
			Type:        "SocialProofCardStatistics",
			HideFromNav: false,
			Library:     "FlowBite",
			Heading:     "Social Proof Card Statistics",
			Subheading:  "We are a team of developers and designers who are passionate about creating beautiful and functional websites.",
			Note:        "Results based on a composite organization of 1,800 developers using GitHub over three years.",
			Sentiment:   "positive",
			Statistics: Statistics{
				Left: Statistic{
					Value:       "40%",
					Title:       "Reduction",
					Description: "in developer onboarding time",
				},
				Center: Statistic{
					Value:       "469%",
					Title:       "Return on investment",
					Description: "over 3 years",
				},
				Right: Statistic{
					Value:       "60+",
					Title:       "Minutes saved",
					Description: "per developer, per day",
				},
			},
		},
		&StyledQuiz{
			Identifier:  "styled_quiz_windows_container_ci_solution_finder",
			Type:        "StyledQuiz",
			HideFromNav: false,
			Library:     "FlowBite",
			Heading:     "Windows Container CI Solution Finder",
			Subheading:  "Let us help you find the right CI solution for your Windows containers",
			Questions: []QuizQuestion{
				{
					ID:          "1",
					Title:       "Your Details",
					Description: "Please share your contact information so we can provide personalized recommendations.",
					Type:        "form",
					Fields: []Field{
						{
							Type:        "text",
							Label:       "Full Name",
							ID:          "full-name",
							Placeholder: "John Smith",
						},
						{
							Type:        "email",
							Label:       "Work Email",
							ID:          "email",
							Placeholder: "john@company.com",
						},
						{
							Type:        "text",
							Label:       "Company Name",
							ID:          "company",
							Placeholder: "Acme Corp",
						},
						{
							Type:  "checkbox",
							Label: "I agree to be contacted about Windows container CI solutions",
							ID:    "consent",
						},
					},
				},
				{
					ID:          "2",
					Title:       "Current CI Setup",
					Description: "What CI system are you currently using for Windows containers?",
					Type:        "radio",
					Options: []Option{
						{ID: "jenkins", Label: "Jenkins"},
						{ID: "azure-devops", Label: "Azure DevOps"},
						{ID: "github-actions", Label: "GitHub Actions"},
						{ID: "gitlab", Label: "GitLab CI"},
						{ID: "other", Label: "Other"},
						{ID: "none", Label: "Not using CI for Windows containers yet"},
					},
				},
				{
					ID:          "3",
					Title:       "Container Types",
					Description: "What types of Windows containers are you working with?",
					Type:        "radio",
					Options: []Option{
						{ID: "windows-server-core", Label: "Windows Server Core containers"},
						{ID: "nano-server", Label: "Nano Server containers"},
						{ID: "mixed", Label: "Mix of Linux and Windows containers"},
						{ID: "planning", Label: "Still planning our container strategy"},
					},
				},
				{
					ID:          "4",
					Title:       "Build Time",
					Description: "How long do your Windows container builds typically take?",
					Type:        "radio",
					Options: []Option{
						{ID: "under-10", Label: "Under 10 minutes"},
						{ID: "10-30", Label: "10-30 minutes"},
						{ID: "30-60", Label: "30-60 minutes"},
						{ID: "over-60", Label: "Over 60 minutes"},
					},
				},
				{
					ID:          "5",
					Title:       "Main Challenges",
					Description: "What's your biggest challenge with Windows container CI?",
					Type:        "radio",
					Options: []Option{
						{ID: "build-time", Label: "Slow build times"},
						{ID: "cost", Label: "High infrastructure costs"},
						{ID: "compatibility", Label: "Compatibility issues"},
						{ID: "complexity", Label: "Complex configuration"},
						{ID: "reliability", Label: "Build reliability"},
					},
				},
				{
					ID:          "6",
					Title:       "Team Size",
					Description: "How many developers work with Windows containers in your team?",
					Type:        "radio",
					Options: []Option{
						{ID: "small", Label: "1-5 developers"},
						{ID: "medium", Label: "6-20 developers"},
						{ID: "large", Label: "21-50 developers"},
						{ID: "enterprise", Label: "50+ developers"},
					},
				},
				{
					ID:          "7",
					Title:       "Timeline",
					Description: "When are you looking to implement or upgrade your Windows container CI solution?",
					Type:        "radio",
					Options: []Option{
						{ID: "immediate", Label: "Immediately"},
						{ID: "this-quarter", Label: "This quarter"},
						{ID: "next-quarter", Label: "Next quarter"},
						{ID: "exploring", Label: "Just exploring options"},
					},
				},
			},
		},
		&StyledQuiz{
			Identifier:  "styled_quiz_modular",
			Type:        "StyledQuiz",
			HideFromNav: false,
			Library:     "FlowBite",
			Heading:     "Get Started with Flowbite",
			Subheading:  "Answer a few questions to get personalized recommendations",
			Questions: []QuizQuestion{
				{
					ID:          "1",
					Title:       "Personal Info",
					Description: "Please fill in your personal information.",
					Type:        "form",
					Fields: []Field{
						{
							Type:        "text",
							Label:       "Full Name",
							ID:          "full-name",
							Placeholder: "Bonnie",
						},
						{
							Type:        "email",
							Label:       "Your email",
							ID:          "email",
							Placeholder: "name@company.com",
						},
						{
							Type:  "checkbox",
							Label: "I agree to the Terms of Use and Privacy Policy",
							ID:    "terms",
						},
					},
				},
				{
					ID:          "2",
					Title:       "Launch Time",
					Description: "How long does it typically take your team to launch a new landing page?",
					Type:        "radio",
					Options: []Option{
						{ID: "less-than-a-day", Label: "Less than a day"},
						{ID: "1-3-days", Label: "1-3 days"},
						{ID: "4-7-days", Label: "4-7 days"},
						{ID: "more-than-a-week", Label: "More than a week"},
					},
				},
				{
					ID:          "3",
					Title:       "PageSpeed Score",
					Description: "What's your current Google PageSpeed score?",
					Type:        "radio",
					Options: []Option{
						{ID: "dont-know", Label: "I don't know"},
						{ID: "less-than-30", Label: "Less than 30"},
						{ID: "30-60", Label: "30-60"},
						{ID: "60-90", Label: "60-90"},
						{ID: "90-plus", Label: "90+"},
					},
				},
				{
					ID:          "4",
					Title:       "Engineering Involvement",
					Description: "How often do marketers need to involve engineers for landing page updates?",
					Type:        "radio",
					Options: []Option{
						{ID: "never", Label: "Never"},
						{ID: "major-changes", Label: "Only for major changes"},
						{ID: "most-changes", Label: "For most changes"},
						{ID: "every-change", Label: "For almost every change"},
					},
				},
				{
					ID:          "5",
					Title:       "Team Frustration",
					Description: "Which best describes your team's frustration with the current landing page process?",
					Type:        "radio",
					Options: []Option{
						{ID: "marketing-waiting", Label: "Marketing is constantly waiting on engineering"},
						{ID: "engineering-interrupted", Label: "Engineering is frequently interrupted by marketing requests"},
						{ID: "both-frustrated", Label: "Both teams are frustrated with the process"},
						{ID: "process-works", Label: "Our process works well for everyone"},
					},
				},
				{
					ID:          "6",
					Title:       "Version Control",
					Description: "How do you currently handle version control for landing pages?",
					Type:        "radio",
					Options: []Option{
						{ID: "no-version-control", Label: "We don't use version control"},
						{ID: "cms-version-control", Label: "Through our CMS"},
						{ID: "manual-backups", Label: "Manual backups"},
						{ID: "git-version-control", Label: "Git or similar system"},
					},
				},
				{
					ID:          "7",
					Title:       "Page Load Speed",
					Description: "How important is page load speed to your business?",
					Type:        "radio",
					Options: []Option{
						{ID: "critical", Label: "Critical - we measure and optimize regularly"},
						{ID: "important", Label: "Important - we try to keep pages fast"},
						{ID: "somewhat", Label: "Somewhat important - we check occasionally"},
						{ID: "not-priority", Label: "Not a priority right now"},
					},
				},
				{
					ID:          "8",
					Title:       "Engineering Tools",
					Description: "Which tools do your engineers currently use?",
					Type:        "radio",
					Options: []Option{
						{ID: "git", Label: "Git"},
						{ID: "component-libraries", Label: "Component libraries (like Flowbite, Preline UI)"},
						{ID: "custom-components", Label: "Custom component system"},
						{ID: "static-generators", Label: "Static site generators"},
						{ID: "traditional-cms", Label: "Traditional CMS (WordPress, Drupal, etc.)"},
					},
				},
				{
					ID:          "9",
					Title:       "Marketing Workflow",
					Description: "How does your marketing team prefer to work?",
					Type:        "radio",
					Options: []Option{
						{ID: "visual-only", Label: "Visual editors only"},
						{ID: "basic-html", Label: "Comfortable with basic HTML/CSS"},
						{ID: "mixed", Label: "Mix of visual and code editing"},
						{ID: "through-devs", Label: "Primarily through developers"},
					},
				},
			},
		},
	}
}
