_schema: _schema
source: /src/
paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: _data
    name: Data
    icon: data_usage
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
editor:
  default_path:
timezone: Europe/London
markdown:
  engine: commonmark
  options:
    html: true
